import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { getApiLimitCount } from "@/lib/api-limit";
import { checkSubscription } from "@/lib/subscription";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Ai Generation",
    description: "Generated by Ai",
  };

const DashboardLayout = async (
    {children}:{children:React.ReactNode}
) => {

    const apiLimitCount = await getApiLimitCount()
    const isPro = await checkSubscription()

    return ( 
        <div className="h-full relative">
            <div className="hidden f-full md:w-72 md:flex md:flex-col md:fixed md:inset-y-0 bg-gray-900">
                <Sidebar 
                    isPro={isPro}
                    apiLimitCount={apiLimitCount} />
            </div>
            <main className="md:pl-72">
                <Navbar />
                {children}
            </main>
        </div>
     );
}
 
export default DashboardLayout;